baseURL = 'https://marlonnl.github.io/'
locale = 'pt-br'
title = 'apupos'
theme = 'paper'

[hugo]
titleCaseStyle = 'none'
capitalization = 'none'

[taxonomies]
tag = "tags"
category = "categories"

[params]
color = 'linen'

instagram = 'marlonn'
rss = true

bio = 'coleção de links e notas'


[[menus.main]]
  identifier = "categorias"
  name = "categorias"
  url = "/categories/"
  weight = 20

[[menus.main]]
  identifier = "tags"
  name = "tags"
  url = "/tags/"
  weight = 30

[[menus.main]]
  identifier = "sobre"
  name = "sobre"
  url = "/about/"
  weight = 10