baseURL = 'https://marlonnl.github.io/'
locale = 'pt-br'
title = 'apupos'
theme = 'paper'

[hugo]
titleCaseStyle = 'none'
capitalization = 'none'

[taxonomies]
tag = "tags"
category = "categories"

[params]
color = 'linen'

instagram = 'marlonn'
rss = true

bio = 'coleção de links e notas'